"""
Django settings for foodproject project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from django.contrib.messages import constants as messages
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n2*5td0qs3kaw&-^ob+izmyc_^1cu$atr=jwqy4**n*($pg_(3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'foodapp',
    'vendor'
]
X_FRAME_OPTIONS='SAMEORIGIN'

SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'foodproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foodproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'food_app',
        'USER': 'postgres',
        'PASSWORD': 'kanhu',
        'HOST': 'localhost',
    }
}

AUTH_USER_MODEL = 'accounts.User'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
import os


#Static files
STATIC_DIR = BASE_DIR / 'static'

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # TO add the collectstatic (change the admin panel design) /// It's use for deployement it will copy all satic folder to one folder


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')

# MEDIA_DIR = BASE_DIR / 'media'
# MEDIA_ROOT = MEDIA_DIR
# MEDIA_URL = '/media/'

# MEDIA_ROOT = [BASE_DIR / 'media/user']
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# MEDIA_URL = '/media/'
# MEDIA_URL = '/mediafiles/'
# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),'mediafiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}




EMAIL_HOST='smtp.@gmail.com'
EMAIL_PORT=25
EMAIL_HOST_USER='foodmonster@gmail.com'
EMAIL_HOST_PASSWORD='Soubhagya1.'
EMAIL_USE_TLS=True
# EMAIL_HOST_TLS= True


# LOGIN_REDIRECT_URL = 'index'
# LOGOUT_REDIRECT_URL = 'index'
# LOGIN_URL = "login"
# MIDDLEWARE_CLASSES = (
#     "‘django.middleware.csrf.CsrfViewMiddleware’",
#     "‘django.middleware.common.CommonMiddleware’",
#     "‘django.contrib.sessions.middleware.SessionMiddleware’",
# "    ‘django.contrib.auth.middleware.AuthenticationMiddleware’",
#  "   ‘django.contrib.messages.middleware.MessageMiddleware’",
# )


# csrf_cookie_secure ?
# CSRF_COOKIE_SECURE = True

# CSRF_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SECURE = True
